### ISSUE TITLE
Where is EvoCrash code source ?

### ISSUE THREAD

**Issue by MaelAudren** [STAMP-project/EvoCrash-demo#10]
I suppose that EvoCrash uses [EvoSuite](https://github.com/EvoSuite/evosuite). However I don't see the code source of EvoCrash here. 
1/ Is this repository only dedicated to do demo ?
2/ Is EvoCrash opensource ? If it is can I have the link of the code source ?

**Comment by pderakhshanfar** [comment]
This repository is a demo about using EvoCrash (you can find some samples in src/test directory). The source code is not availabe here, but you can find EvoCrash jar file in evocrash-lib directory. EvoCrash is not opensource right now, but it will be soon.

**Comment by MaelAudren** [comment]
Thanks a lot for the clarification.

**Comment by pderakhshanfar** [comment]
The source code is available in STAMP repository. You can find it here:
https://github.com/STAMP-project/EvoCrash
