### ISSUE TITLE
To ease readability/debugging

### ISSUE THREAD

**Issue by mbenguig** [STAMP-project/EvoCrash-demo#13]
Improvements:

The first difficulties we encountered were related to malformed log files. Indeed, exceptions do not clearly expose the reason.

Target exception was set to: com.fasterxml.jackson.core.JsonParseException LogParser: Failed to parse the log file!
* Computation finished

In a perfect world, user would directly analyze log files without pre processing.

The test generation execution trace requires more meaningful messages, to clearly distinguish ML related steps. Moreover, some logs are not required for a default utilization and could be enabled at a higher log level. This latter could be set from a dedicated property file. The notion of budget was not clear until i found its definition on the evosuite website.

**Comment by pderakhshanfar** [comment]
In EvoCrash case, the log file is the stack trace. This exception happens when the stack trace directory did not set right. About the properties, I sent you a link for understanding properties better. I will send it here again. Each of the properties has a description in front of it.

https://github.com/EvoSuite/evosuite/blob/master/client/src/main/java/org/evosuite/Properties.java

**Comment by PascalUrso** [comment]
Sure, but the error "Target exception was set to: com.fasterxml.jackson.core.JsonParseException LogParser: Failed to parse the log file!" could be more informative / user friendly

**Comment by pderakhshanfar** [comment]
Yes, I agree with you that we should improve the informativity of the output. We will take care of that after completing our studies about crash replication with EvoCrash. There are lots of paths that we can work on them for improving the rate of crash replication.

**Comment by xdevroey** [comment]
The exception is thrown by the [LogParser](https://github.com/STAMP-project/EvoCrash/blob/master/client/src/main/java/org/evosuite/coverage/evocrash/LogParser.java) class. EvoCrash being a research tool, the user feedback is indeed sometimes limited, sorry. If you have some time, please do not hesitate to contribute here, it will be much appreciated :-)

In the meantime, if you send us a copy of the log file (or put it here in an answer), we should be able to tell you what goes wrong.

**Comment by xdevroey** [comment]
See https://github.com/STAMP-project/EvoCrash/issues/5 and https://github.com/STAMP-project/EvoCrash/issues/6
