### ISSUE TITLE
"Getting Started" not working for me

### ISSUE THREAD

**Issue by ltboye** [STAMP-project/EvoCrash-demo#4]
To get started with EvoCrash, I tried following the instructions. I'm not sure how to do it on a Windows system, but I started, using Git Bash. I got as far as the first java execution:
java -cp ../evocrash-lib/evocrash-1.0.0.jar:. org.junit.runner.JUnitCore test.XWIKI_13916_Test
This crashes with a large trace, attached.
[output.txt](https://github.com/STAMP-project/EvoCrash/files/1571767/output.txt)

**Comment by pderakhshanfar** [comment]
There is a separator for paths of project dependencies. for Unix based OS the separator is ":", but for Windows it is ";". If you want to run any case on Windows, you need to change the separator from ":" to ";".  For instance, in XWIKI_13916 you need to replace the separator at Line 42 in XWIKI_13916_Test.java to ";".

**Comment by ltboye** [comment]
I still don't get very far. I think I need an online session with some guidance to get this working.

**Comment by assadOW2** [comment]
Hi,
I have also an issue, it is in zookeeper-3.4.6.jar but it happens to me after manually editing the java file and running this command: java -cp ../evocrash-lib/evocrash-1.0.0.jar:../src/test:"$(cat xwikiclasspath.txt)" org.junit.runner.JUnitCore com.xpn.xwiki.objects.classes.BaseClass_ESTest
[evocrash_output.txt](https://github.com/STAMP-project/EvoCrash/files/1642435/evocrash_output.txt)

I attached the whole output. My OS is Ubuntu 16.04 LTS.
Thanks in advance for your answer.

**Comment by pderakhshanfar** [comment]
@ltboye Sure, We can have online session whenever you want. In general, it works better for me to have this session in February.

**Comment by pderakhshanfar** [comment]
@ltboye @assadOW2 Lets run EvoCrash on TellU and OW2 cases. When are you available for a Skype call?

**Comment by assadOW2** [comment]
@pderakhshanfar : I am available this afternoon or friday this week. Thanks for your help.

**Comment by ltboye** [comment]
Next week would be good for me. I am available most of the time next week, except Thursday.

**Comment by pderakhshanfar** [comment]
@assadOW2 shall we do it on Friday? I am flexible about the time.

**Comment by pderakhshanfar** [comment]
@ltboye Next week is ok. Is Monday afternoon ok?

**Comment by assadOW2** [comment]
@pderakhshanfar : I am flexible too, we can do it in the morning at 10 am or afternoon at 2 pm, tell me which one suits you better.

**Comment by pderakhshanfar** [comment]
Friday morning works better for us.

**Comment by assadOW2** [comment]
@pderakhshanfar : ok, so let's do it tomorrow morning ! Thanks.

**Comment by pderakhshanfar** [comment]
Ok. this is my Skype id: pooria.derakhshanafar

**Comment by ltboye** [comment]
@pderakhshanfar Yes, I am available 14:00 - 16:00

**Comment by pderakhshanfar** [comment]
@ltboye So, I think we can start the meeting at 14:00.

**Comment by ltboye** [comment]
@pderakhshanfar OK! I see your Skype id. Mine is ltboye

**Comment by ltboye** [comment]
A little report to wrap up this issue, now that we have had a Skype session.

The "Getting started" does not work on Windows. Path separators needed changing from ':' to ';', and there was also an issue with the path in XWIKI_13916_Test. We still couldn't get it running from command line (seems it didn't find JUnit).

We got it working in Eclipse. XWIKI_13916_Test ran, but did not complete. Probably ran out of resources. Tried XWIKI_13031_Test, which completed, generating a test which replicated the frames of the stack trace.

Suggestions for improving the GitHub documentation:
- There should be some information about what EvoCrash and the GitHub project is. At least a link to more information.
- A "Getting started" which works on windows, or pointing out the issues running on Windows.

**Comment by MaelAudren** [comment]
I have a stacktrace which really like @ltboye one. 

I managed to solve the issue by removing the EvoRunner annotation and the try catch block before compiling. In the README.md the compilation step comes before the manual file change. 
Could you confirm that it is an issue from the README.md or did I misunderstood something ?

**Comment by pderakhshanfar** [comment]
Hi @MaelAudren. Yes, that was a mistake. I fixed it.
If you need more help to apply EvoCrash to other cases we can have an online session about that.
